name: flutter_html_view
description: Flutter Plugin to render html, Flutter has no default support to render html so this package helps you to render your html to native widgets
version: 0.5.11
author: Karthik Ponnam <ponnamkarthik3@gmail.com>
homepage: https://github.com/PonnamKarthik/FlutterHtmlView

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^1.2.0
  flutter_custom_tabs:
    git: git://github.com/ohze/flutter_custom_tabs.git
  html: ^0.14.0+2
  video_player: 0.10.1+6
  cached_network_image: ^1.1.1
  flutter_cache_manager: ^1.1.1

  flutter_markdown:
    path: flutter_markdown/
  html2md:
    path: html2md/


environment:

  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"
